### ISSUE TITLE
write method doesn't work after a few call

### ISSUE THREAD

**Issue by polaroi8d** [BleepLabs/S25FLx#2]
First of all, thanks for your work. Your lib is working perfectly but If I call a flash.write() method after 2x time the third time is this not working. 

I am increment the starter location in the first params but I don't know what am I missing.  

Here is my code snippet: 
```
              if (memoryIndex == PAGE_SIZE-1) {
                if (memoryPage == 0) {
                  FLASH.write(0, writeBuffer, PAGE_SIZE);
                } else if (!memoryPage == 0) {
                  FLASH.write(((memoryPage*PAGE_SIZE)+memoryPage), writeBuffer, PAGE_SIZE);
                }
                FLASH.waitforit();
                Serial.println(F("1 page was written on the Flash memory."));
                memoryIndex = 0;
                memoryPage++;
              } else {
                memoryIndex++;
              }
```

**Comment by BleepLabs** [comment]
Hello,
What flash chip are you using? Are you running this on an UNO or Teensy or?
If you're on Teensy I would recommend the serial flash library for it.

**Comment by polaroi8d** [comment]
Hello @BleepLabs first of all thanks for your reply. I am using an S25FL032P 32MBit 3.0V Flash memory and programming to Arduino, this is the only libary which is working for me "perfectly" excpect this little issue.

**Comment by BleepLabs** [comment]
This might be the issue
`(memoryPage*PAGE_SIZE)+memoryPage)`
`+memory page` shifts the location into the next page. Just `(memoryPage*PAGE_SIZE)` should work

This makes sense as a memoryPage of 0 would just write in the 0 page. 1 starts on the "1" byte of page 1 and writes a single byte to page 2. Then page 2 is going to fail.
